### PR TITLE
:fix MM injected browser not showing on ethers 

### LINKED ISSUE #3244: [bug] METAMASK CONNECT FAILED: ConnectorController.setConnectors: Not possible to add connector
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/cranky-sara-m9n7qz?workspaceId=a5758ebb-9135-49f0-b708-70855cec901f

### Summary

image

At the moment, there are three conditions in which I cannot connect to Metamask, since the modal window shows that the wallet is not installed

1. Using any iframe on the site that loads before the initialization of the modal connection window - causes an error as shown in the screenshot. Attached a sundbox with reproduction of this bug.
2. Also encountered a similar problem but with GTM. If GTM loads before the connection window - I see the absence of a wallet. Most likely because GTM adds something like a pixel that integrates the iframe to track user actions. so i think its the same case (look at point 1)
3. I also encountered a very strange problem associated with the number of reactive variables in the application. In my case, I added the connection window dynamically - after certain actions, and when my application became much larger (there were more reactive variables), Metamask stopped displaying. I received an error of this format
image

Problem number 3 will be quite difficult to reproduce, but perhaps it is all somehow connected. And unfortunately I can't show my code so that you can study it

The problem is very critical and I hope it will be solved as soon as possible.

### List of related npm package versions

tested on all latest versions, nothing works

 "@reown/appkit": "^1.4.0",
 "@reown/appkit-adapter-ethers": "^1.4.0",

### PR DESCRIPTION
**Pull request by svenvoskamp**
# Description

Fixed an issue where MM injected browser doesn't show up on ethers

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Associated Issues

For Linear issues: Closes APKT-xxx
For GH issues: closes #3244

# Showcase (Optional)

If there is a UI change include the screenshots with before and after state.
If new feature is being introduced, include the link to demo recording.

# Checklist

- [ ] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [ ] My changes generate no new warnings
- [ ] I have reviewed my own code
- [ ] I have filled out all required sections
- [ ] I have tested my changes on the preview link
- [ ] Approver of this PR confirms that the changes are tested on the preview link

### CODE REVIEW

**Review by magiziz — APPROVED** [review]

File: packages/core/src/controllers/ConnectorController.ts [hunk 1]
```diff
@@ -32,33 +32,26 @@ export const ConnectorController = {
...
+        )
+    )
+
+    /**
+     * We are reassigning the state of the proxy to a new array of new objects, this can cause issues. So it is better to use ref in this case.
+     * Check more about proxy on https://valtio.dev/docs/api/basic/proxy#Gotchas
+     * Check more about ref on https://valtio.dev/docs/api/basic/ref
+     */
+    newConnectors.forEach(connector => {
+      state.allConnectors.push(ref(connector))
```
Comment (enesozturk) [inline packages/core/src/controllers/ConnectorController.ts:52]: Exactly.. When working with non primitive values, `ref` must be used for Valtio states. Such a good catch 🙏🏽

**Review by enesozturk — APPROVED** [review]

**Comment by elix1er** [comment]
please deploy to NPM @svenvoskamp
